# Generated by Django 5.0 on 2024-11-25 13:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAiModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        default="gpt-4o-mini",
                        max_length=200,
                        unique=True,
                        verbose_name="Model Name",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Assistant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, null=True, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "assistant_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Assitant Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("instructions", models.TextField(verbose_name="Instructions")),
                (
                    "is_global",
                    models.BooleanField(default=False, verbose_name="Is Global"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistants",
                        to="assistants.openaimodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssistantFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_id",
                    models.CharField(
                        max_length=200, null=True, unique=True, verbose_name="File ID"
                    ),
                ),
                ("name", models.CharField(max_length=400, verbose_name="File Name")),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        null=True, verbose_name="File Size In Bytes"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        default="assitant", max_length=100, verbose_name="Purpose"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="assistant/files",
                        verbose_name="File",
                    ),
                ),
                (
                    "assistant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="assistants.assistant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssistantTool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("code_interpreter", "Code Interpreter"),
                            ("function", "Function"),
                            ("retrieval", "Retrieval"),
                        ],
                        default="retrieval",
                        max_length=50,
                        verbose_name="Tool Type",
                    ),
                ),
                (
                    "function_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Function Name",
                    ),
                ),
                (
                    "function_logic",
                    models.TextField(
                        blank=True, null=True, verbose_name="Function Logic"
                    ),
                ),
                (
                    "function_descriptor",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="Function OpenAPI descriptor",
                    ),
                ),
                (
                    "assistant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assistants.assistant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssistantVectorStore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Vector Store Name"),
                ),
                (
                    "vector_store_id",
                    models.CharField(
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="Vector Store ID",
                    ),
                ),
                (
                    "assistant",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_stores",
                        to="assistants.assistant",
                    ),
                ),
                (
                    "files",
                    models.ManyToManyField(
                        related_name="vector_stores", to="assistants.assistantfile"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_vector_stores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
